[project]
name = "voicesofpyladiesmanila"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "air-convert>=0.3.0",
    "air[standard]>=0.34.0",
]
